# Generated by Django 3.2.3 on 2021-07-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaewon', '0002_alter_porfolio_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfolio',
            name='image',
        ),
    ]
